In [1]:
import sys
sys.path.append('C:/Users/sliso/LastTradingProject_7052026/indicators')

In [2]:
import pandas as pd
import numpy as np
from numba import njit
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from SignalDecorator import signal  # your decorator
from GarmanKlass import GarmanKlass

In [3]:
data=pd.read_csv("../df_test.csv", parse_dates=['Date'], index_col='Date')

In [4]:
data

                        Open     High      Low    Close  Volume
Date
2018-01-01 22:00:00  1.20071  1.20121  1.20044  1.20106      98
2018-01-01 22:15:00  1.20106  1.20132  1.20059  1.20074     126
2018-01-01 22:30:00  1.20076  1.20174  1.20076  1.20152      66
2018-01-01 22:45:00  1.20164  1.20168  1.20143  1.20152      48
2018-01-01 23:00:00  1.20148  1.20153  1.20019  1.20148    1792
...                      ...      ...      ...      ...     ...
2019-12-31 20:45:00  1.12156  1.12182  1.12155  1.12177      67
2019-12-31 21:00:00  1.12174  1.12174  1.12141  1.12148      36
2019-12-31 21:15:00  1.12146  1.12150  1.12141  1.12146      21
2019-12-31 21:30:00  1.12148  1.12152  1.12139  1.12139      23
2019-12-31 21:45:00  1.12136  1.12138  1.12102  1.12120      57

[49701 rows x 5 columns]

In [5]:
data

                        Open     High      Low    Close  Volume
Date
2018-01-01 22:00:00  1.20071  1.20121  1.20044  1.20106      98
2018-01-01 22:15:00  1.20106  1.20132  1.20059  1.20074     126
2018-01-01 22:30:00  1.20076  1.20174  1.20076  1.20152      66
2018-01-01 22:45:00  1.20164  1.20168  1.20143  1.20152      48
2018-01-01 23:00:00  1.20148  1.20153  1.20019  1.20148    1792
...                      ...      ...      ...      ...     ...
2019-12-31 20:45:00  1.12156  1.12182  1.12155  1.12177      67
2019-12-31 21:00:00  1.12174  1.12174  1.12141  1.12148      36
2019-12-31 21:15:00  1.12146  1.12150  1.12141  1.12146      21
2019-12-31 21:30:00  1.12148  1.12152  1.12139  1.12139      23
2019-12-31 21:45:00  1.12136  1.12138  1.12102  1.12120      57

[49701 rows x 5 columns]

In [6]:
gktest=GarmanKlass(data)

In [7]:
gktest.plot(1200,1500)

In [ ]:
df=pd.read_csv("../all_data_EUR_USD.csv", parse_dates=['Date'], index_col='Date')